project:
  type: website
  
website:
  title: "RSF COMPUTING SERVICES"
  navbar:
    left:
      - href: https://rsfintranet.org/
        text: "Back to RSF Intranet"
  sidebar: 
    collapse-level: 1
    contents: 
    - section: Welcome
      contents: 
        - index.qmd
    - section: More Info
      contents: 
        - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: scroll
    
editor: visual


